version: '3.8'

services:
   vite-app:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 5173:5173 # Map the Vite development server port
      volumes:
         - .:/app # Mount the project directory
         - /app/node_modules # Avoid overwriting the container's node_modules
      command: npm run dev -- --host
      environment:
         - NODE_ENV=development

           # docker-compose.yml for production:
# version: '3.8'

# services:
#   vite-app:
#     build:
#       context: .
#       dockerfile: Dockerfile.prod
#     ports:
#       - "80:80"
